### ISSUE TITLE
Forums options--"Watch"

### ISSUE THREAD

**Issue by heatherahans** [DukeLearningInnovation/duke-sakai-skins#23]
In the Forums, one of the options is “Watch,” but I’m not sure a user would understand what that means… it might be a good idea to discuss renaming that option... “Notifications” would be more universally understood. (Of course, user testing would be helpful, but I'm not sure if you'd want to do that for just this option.)

**Comment by profmikegreene** [comment]
![sakai___administration_workspace___message_bundle_manager](https://user-images.githubusercontent.com/3632822/44551292-b4c76e80-a6f4-11e8-82f1-08809874a41a.png)
It looks like we could resolve this through Message Bundle Manager. @joliet do you want me to add this to basecamp for UX of some kind?

**Comment by joliet** [comment]
Yes, we are already UX testing Forums this fall, probably first. This issue was identified by the Forums Improvement Project.

Are we tracking these recommendations here or in our Sakai Improvements Form?  Speaking of the form, should we delete what is there since we’ve moved those out to our working doc?
